### ISSUE TITLE
Possible spoof package on NPM

### ISSUE THREAD

**Issue by pbugnion** [quigleyj97/jupyterlab-spreadsheet#12]
Hi!

I maintain [jupyterlab-sql](https://github.com/pbugnion/jupyterlab-sql), which is published on Pypi. The JS code is bundled into the Python package, so I don't need to distribute it separately.

I recently noticed that someone parked the [package name on NPM](https://www.npmjs.com/package/jupyterlab-sql) with a legit looking README and version number. Unless I'm missing something, the same person has done this for [jupyterlab-xlsx](https://www.npmjs.com/package/jupyterlab-xlsx).

Is this something you're aware of? Do you have any thoughts on how to deal with it?

**Comment by pbugnion** [comment]
Update: I have sent a support request to NPM to inform them of this. I'll post here when I have updates.

**Comment by quigleyj97** [comment]
This is the first I've heard of it, thanks for digging this up. I'll download the packages to an empty folder and see what's in them. It looks like `jupyterlab-clipboard` is also typosquatted as [`jupyterlab-imgclip`](https://www.npmjs.com/package/jupyterlab-imgclip)

**Comment by quigleyj97** [comment]
After poking at it briefly, this appears to just be a straight clone. There's no diffs between jupyterlab-imgclip and jupyterlab-clipboard, aside from some TSC artifacts (like the generated async helper) and package.json entries. Similar story for jupyterlab-spreadsheet, though the xlsx author pulled from a branch instead of master. So it looks like there's no security risk (though we can't make that guarantee looking forwards).

I think some people do this as resume-padding or something; I've had 1 fork and a few stars from users that just fork and star everything under the sun.

**Comment by pbugnion** [comment]
Thanks for looking into it. It's a relief that you don't think there's no security risk.

I'd still like it taken down since users are accidentally installing from NPM instead of Pypi. I'll post here when NPM get back to me.

**Comment by dhirschfeld** [comment]
I'd like all squatted packages to be taken down as it's very dangerous for users - there's nothing stopping the author from pushing malware once they've gained some users.

The `jupyterlab-` prefix and the fact that they work and provide the same functionality gives them an air of legitimacy that could easily fool an unsuspecting user who just googled e.g. *"jupyterlab excel"*

**Comment by jasongrout** [comment]
Perhaps the person that pushed them to npm realized that you hadn't published them (since you are including the js source in your python packages), and pushed them to npm to help people?

Perhaps the first thing to do is to email the author of the npm packages and ask them if you could have the name back and promise to publish. In other words, assume good intent and that they were trying to help the community, and it would be less of a burden to them if you published them yourself.

You could put a `private: true` field in your package.json to prevent straight clones from being pushed to npm, but of course that wouldn't help if someone just removed that field, then published to npm.

**Comment by pbugnion** [comment]
@jasongrout thanks for the feedback.

> Perhaps the person that pushed them to npm realized that you hadn't published them (since you are including the js source in your python packages), and pushed them to npm to help people?

Since `jupyterlab-sql` includes a server extension, there is presumably no way I can distribute the package through NPM (unless I'm missing something)? In this case, users that install from NPM just end up with a broken installation that is harder to get out of.

**Comment by pbugnion** [comment]
NPM have replied. They suggest [following their disputes policy](https://www.npmjs.com/policies/disputes). Basically, we email the package owner (they provided us with an email address), and cc `support@npmjs.com`. If nothing is done within 4 weeks, support will step in and arbitrate.

@quigleyj97 do you want to write a joint email? I was thinking of sending something like the following. What do you think?

>>> Dear Weiyan,

We recently noticed that you are hosting packages [jupyterlab-xlsx](https://www.npmjs.com/package/jupyterlab-xlsx) and [jupyterlab-sql](https://www.npmjs.com/package/jupyterlab-sql) on your NPM account. By looking at the README, the transpiled sources and the VCS URL, these are just straight clones of the package [jupyterlab-sql](https://github.com/pbugnion/jupyterlab-sql), hosted on Pypi, and [jupyterlab-spreadsheet](https://github.com/quigleyj97/jupyterlab-spreadsheet), hosted on NPM.

While I'm sure this was done with the best intentions, having separate versions of these packages can be confusing for users:

- for *jupyterlab-sql*, this leads to users installing the package from NPM (instead of from Pypi, where they are supposed to install it from). Users are then missing the server extension (see [this issue](https://github.com/pbugnion/jupyterlab-sql/issues/87#issuecomment-508429802)), for instance.
- for *jupyterlab-xls*, this leads to users installing a different version of an extension that is not maintained by the package's official author. As a user, it isn't obvious that I need to install *jupyterlab-spreadsheet*, not *jupyterlab-xls*. Both of these being available through the `jupyter labextension` mechanism is a source of confusion.

We therefore request that you take both jupyterlab-xls and jupyterlab-sql down.

Kind regards,

Joe Quigley (author of jupyterlab-spreadsheet) and Pascal Bugnion (author of jupyterlab-sql)

**Comment by quigleyj97** [comment]
That sounds good to me. You might also want to consider asking for the `jupyterlab-sql` package name to be transferred to you, that way you can head off future confusion. (You can either upload a dummy package that tells users they installed the wrong thing, or upload the client only)

Thank you for taking point on this, and let me know if you need any other help. My email is `quigley (dot) joseph (at) outlook (dot) com`.

**Comment by pbugnion** [comment]
Great! All sent. I'll post here when there's new developments.

**Comment by stonebig** [comment]
any news ?

**Comment by quigleyj97** [comment]
We’re progressing this with NPM Support, and should know more by next week.

As we previously evaluated, the packages pose no current security risk. We advise any Lab users and JupyterHub admins to make sure the spoof packages are not installed on their systems but if they are currently installed, then the only remediation necessary is to uninstall them and install the correct extension. We are monitoring the situation and will update if that changes.

On Aug 4, 2019, at 6:44 AM, stonebig <notifications@github.com<mailto:notifications@github.com>> wrote:


any news ?

**Comment by pbugnion** [comment]
I believe ownership of jupyterlab-xlsx has now been transferred to @quigleyj97 (it looks like you even managed to make a release?) and ownership of jupyterlab-sql has been transferred to me.

**Comment by quigleyj97** [comment]
Yup, that’s right! NPM doesn’t allow you to revoke old versions, so what I did instead is publish a dummy package that just points back to this one.

**Comment by quigleyj97** [comment]
Closing this, since `jupyterlab-xlsx` is now replaced with a dummy package and the spoof `jupyterlab-sql` package has been taken down.
