### ISSUE TITLE
Horizontal scroll bar support?

### ISSUE THREAD

**Issue by jarvisaoieong** [quigleyj97/jupyterlab-spreadsheet#13]
Awesome plugin, thank you.

Is there any plan to support horizontal scroll bars?

**Comment by quigleyj97** [comment]
Hmm, can you share a screenshot? There should already be a scrollbars when needed: 

![scrollbars demo](https://user-images.githubusercontent.com/16925819/61194209-15092b00-a68e-11e9-8e60-436bf1585611.gif)

If you're not seeing that, it could be a CSS bug.

**Comment by jarvisaoieong** [comment]
This sheet has columns a to z but can't see the horizontal scroll bar

![scrollbartest](https://user-images.githubusercontent.com/195635/61194940-92b55100-a6f7-11e9-9626-29ee9a75139a.gif)

**Comment by quigleyj97** [comment]
Ok, definite bug. Thanks for reporting! Could you share what browser/OS are you using? And does this happen with every large spreadsheet or just this one?

**Comment by quigleyj97** [comment]
Closing, can’t reproduce. If you’re still seeing this bug, please comment on this issue with browser/OS/any extensions that you have installed and I’ll reopen
