### ISSUE TITLE
ValueError: This extension does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by akelai** [quigleyj97/jupyterlab-spreadsheet#20]
It doesn't install:

```
$ jupyter labextension install jupyterlab-spreadsheet
An error occured.
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0 @jupyterlab/application
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0 @jupyterlab/apputils
```

**Comment by quigleyj97** [comment]
Unfortunately I’ve dropped the ball on updating for JupyterLab 2.0, my life has been busy the past month. I will begin upgrading tonight when I have some free time, and will ping back when I’ve released an update (probably tomorrow or on Saturday). In the meantime, you can either roll back to the last major version of JupyterLab or temporarily disable jupyterlab-spreadsheet. Either of those options will unblock you for now.

**Comment by akelai** [comment]
No problem if you can't soon (or ever), life is this thing that sometimes happens to get into life sometimes.

**Comment by quigleyj97** [comment]
![Good news, everyone!](https://media.giphy.com/media/3o7abA4a0QCXtSxGN2/giphy.gif)

I just published 0.3.1, which includes support for JupyterLab 2.0. Let me know if you run into any issues!

**Comment by akelai** [comment]
Very good that you succeeded. Though, looks like I can't try it, because Jupyter Lab doesn't build, probably it's a problem on my side, as in the log I see:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
Writing both to let you know, and in case you have any suggestions.

**Comment by akelai** [comment]
I've solved the above problem with:
```
export NODE_OPTIONS=--max-old-space-size=4096
jupyter labextension install jupyterlab-spreadsheet
```
Works fine!
