### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by baimianer** [quigleyj97/jupyterlab-spreadsheet#25]
why jupyterlab-spreadsheet can not be installed successfully ?

[LabBuildApp] Building in /root/miniconda3/share/jupyter/lab
[LabBuildApp] Node v14.2.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /root/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.96s.

[LabBuildApp] > node /root/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /root/miniconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.64s.

[LabBuildApp] > node /root/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: Command failed: /root/miniconda3/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/root/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: null,
  signal: 'SIGKILL',
  output: [ null, null, null ],
  pid: 24906,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/root/miniconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/root/miniconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/root/miniconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/root/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/root/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

**Comment by quigleyj97** [comment]
Hmm. Can you share the output of `jupyter labextension list`?

On top of that, does `jupyter lab build --minimize=False` work?

**Comment by baimianer** [comment]
OK. like this

$jupyter labextension list
JupyterLab v2.1.2
Known labextensions:
   app dir: /root/miniconda3/share/jupyter/lab
        @deathbeds/jupyterlab-fonts v1.0.1  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/latex v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.0  enabled  OK
        @parente/jupyterlab-quickopen v0.5.0  enabled  OK
        ipysheet v0.4.4  enabled  OK
        jupyterlab-drawio v0.7.0  enabled  OK
        jupyterlab-spreadsheet v0.3.2  enabled  OK

Uninstalled core extensions:
    @deathbeds/jupyterlab-fonts
    ipysheet
    jupyterlab-spreadsheet

Build recommended, please run `jupyter lab build`:
    @parente/jupyterlab-quickopen needs to be included in build
    ipysheet needs to be removed from build


and 
$jupyter lab build --minimize=False
[LabBuildApp] JupyterLab 2.1.2
[LabBuildApp] Building in /root/miniconda3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-9v8715m1.log

**Comment by quigleyj97** [comment]
What's the contents of that log file mentioned? That will help pin down where the build failure happened. Though with so many extensions, there may be a conflict somewhere.

Also, I notice that the plugin is appearing under "uninstalled core extensions"... a normal installation shouldn't land anything there, were you trying to setup a dev build?

**Comment by baimianer** [comment]
Thank you very much for your help and  I solved this problem by change a jupyterlab version.Maybe 
the reason is my system memory is less than 4Gb.
