### ISSUE TITLE
Documentation: Clarification of file formats

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [quigleyj97/jupyterlab-spreadsheet#27]
The short description of this package says:

> JupyterLab plugin for viewing spreadsheets, such as Excel and OpenOffice

It is not clear, which formats are supported. Excel can save in various formats and OpenOffice can too. Additionally my tests show, that `.xlsx` can be opened, but not `.ods`. Now I am confused as to what formats are implied by "OpenOffice".

It would be more useful and clear to name the file formats directly instead of the programs, which are able to produce them.

**Comment by quigleyj97** [comment]
The lack of ODS support is an oversight on my part, the underlying sheet parser that this plugin uses is SheetJS and that library has exhaustive support for a number of different formats. However, this extension didn't actually register those file formats with the JupyterLab document registry.

**Comment by quigleyj97** [comment]
Merged a PR adding ODS support. I also clarified the repo description, so it includes actual formats supported.
