### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Cinda-Carol** [quigleyj97/jupyterlab-spreadsheet#31]
hi,

When I am installing jupyterlab-spreadsheet, I have this error:

Building jupyterlab assets (build:prod:minimize)
\Exception in thread Thread-11:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python38\lib\subprocess.py", line 1366, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'cp950' codec can't decode byte 0x8b in position 241: illegal multibyte sequence
An error occured.
IndexError: list index out of range
See the log file for details:  C:\Users\cinda\AppData\Local\Temp\jupyterlab-debug-lnuho3pr.log

what should i do? thanks!

**Comment by quigleyj97** [comment]
Very strange. Can you share the output of `jupyter troubleshoot`?

You can also try running a non-minimized build:

```
jupyter lab build --minimize=False
```

If that fails, you can also try to clean and rebuild:

```
jupyter lab clean
jupyter lab build
```

**Comment by Cinda-Carol** [comment]
[jupyterlab-debug-lnuho3pr.log](https://github.com/quigleyj97/jupyterlab-spreadsheet/files/5908451/jupyterlab-debug-lnuho3pr.log)
thanks for the reply. although i had this error, i still could open excel files afterwards. and i tried to install it in anaconda, didn't have this error message again.

**Comment by quigleyj97** [comment]
Hmm, that error is very strange. It seems like an issue with the JupyterLab shell?

```
  File "c:\users\cinda\appdata\local\programs\python\python38\lib\subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "c:\users\cinda\appdata\local\programs\python\python38\lib\subprocess.py", line 1416, in _communicate
    stdout = stdout[0]

IndexError: list index out of range
```

Earlier in the log, there's this, which I haven't seen before:

```
> node c:\users\cinda\appdata\local\programs\python\python38\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ c:\users\cinda\appdata\local\programs\python\python38\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If you're still facing this, _especially_ if you're facing this with other packages as well, I'd encourage you to file a bug against the JupyterLab package for investigation. Separately, it sounds like given that you were able to open Excel files that this extension installed correctly. I'll close the ticket, but please re-open if you see this again.
