### ISSUE TITLE
Row index

### ISSUE THREAD

**Issue by sho-87** [quigleyj97/jupyterlab-spreadsheet#4]
the plugin starts row indexing at 0, whereas if you open an xls file in Excel, row index starts at 1. Possible to switch this over to match?

Its a minor issue, but can make things a bit confusing when, for example, youre using jupyterlab but someone else is using Excel, and you end up referencing different rows/cells due to the row index mismatch

**Comment by quigleyj97** [comment]
I have a fix for this on master, as part of `4ee6b05` (there was a wider off-by-one error that lopped off the ends of some sheets). My plan is to get #1 and #2 resolved and then pushing that as 0.1.0, but if you'd like I can also release a 0.0.3 with just the off-by-one indexing fix.

**Comment by sho-87** [comment]
no thats fine, was just wondering if a fix was coming at all. glad to hear its planned for a future version!

**Comment by quigleyj97** [comment]
Closing as resolved, I released 0.0.3 which includes this fix. You can upgrade with: `jupyter labextension install jupyterlab-spreadsheet@0.0.3`. Thanks for reporting this issue!

I was hoping to get the sheet picker in this weekend, but it's not *quite* ready yet.
